### PR TITLE
feat: support issues

### LINKED ISSUE #20: Feature Request: Add support for Github Issues
It would be very handy if the renderer also worked in GitHub Issues

Example (this should render in this issue)

$e^{i\pi} + 1 = 0$

Thanks for your work, your extension has been very useful to me.

### PR DESCRIPTION
**Pull request by jucor**
Fix #20 (and bumps version to 0.3.6)

### CODE REVIEW

**Comment by a-lberto** [comment]
Blazing fast response! I thought it would be an easy fix but didn't know where to put my hands on.

Thanks for your help.

**Comment by jucor** [comment]
With pleasure! I'm lucky that I could base myself on #15  as an example :)

**Comment by jucor** [comment]
Also a coincidence that I just happened to need it too, came here, and saw your issue already open. Now we just need @AaronCQL to merge it and push it to the Chrome store if that's OK with him when he has the time :)

**Comment by AaronCQL** [comment]
Lovely work @jucor, and thanks for submitting the issue too @a-lberto. Have just pushed the updated version to the chrome store - will likely be approved in the next few days or so.

**Comment by jucor** [comment]
Amazing, thank you!

**Pull request merged**
